### ISSUE TITLE
Modularity: Extract tasks into separate repos

### ISSUE THREAD

**Issue by backflip** [unic/estatico-nou-archive#3]
# Tasks
- [x] JS: https://github.com/unic/estatico/blob/develop/gulp/js/default.js (include `preset-env`, check out HMR)
- [x] js:lint (based on `eslint`)
- [x] CSS: https://github.com/unic/estatico/blob/develop/gulp/css/default.js → compare to webpack afterwards @alinamelnyk 
- [x] css:lint (based on `sass-lint` or `stylelint`) @Wymowny 
- [x] Probably replace css:colors with https://github.com/Updater/node-sass-json-importer
- [x] SVG sprite: https://github.com/unic/estatico/blob/develop/gulp/media/svgsprite.js @drowka 
- [ ] Iconfont: https://github.com/unic/estatico/blob/develop/gulp/media/iconfont.js
- [ ] Data URIs: https://github.com/unic/estatico/blob/develop/gulp/media/dataurls.js
- [x] Image versions: https://github.com/unic/estatico/blob/develop/gulp/media/imageversions.js
- [x] Font inlining: https://github.com/unic/estatico/blob/develop/gulp/css/fonts.js @orioltf 
- [x] Copy (generic, not bound to media files): https://github.com/unic/estatico/blob/develop/gulp/media/copy.js
- [x] Modernizr: https://github.com/unic/estatico/blob/develop/gulp/js/modernizr.js
- [x] JS tests: Based on Puppeter and QUnit (for now): https://github.com/jonkemp/gulp-qunit/issues/31#issuecomment-347005021
- [x] JSON mocks: https://github.com/unic/estatico/blob/develop/gulp/js/mocks.js
- [x] Scaffolding: Evaluate https://github.com/amwmedia/plop and Yeoman, e.g.
- [x] Serve: Based on `browsersync`
- [x] Watch

# Examples:
* https://github.com/unic/estatico-nou/packages/

# Criteria:
* [Exporting task factory](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L53)
  * Taking options overwriting defaults as argument. Defaults for a "standard" gulp task:
    * [`src`](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L14): Which files to read
    * [`srcBase`](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L15): See [docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase)
    * [`dest`](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L16): Where to write to
    * [`plugins`](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L17-L49): Passed to specific gulp plugins
    * [`logger`](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L50): Used for infos, debugging and errors. Most probably an instance of [estatico-utils](https://github.com/unic/estatico-lerna/tree/master/packages/estatico-utils)'s `Logger`
  * Exposing options for everything configurable. Setting plugin options to `null` should [disable the corresponding step](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L132)
  * Returning a gulp stream in case of "standard" gulp tasks. Most probably returning a promise otherwise since we don't want to deal with callbacks.
  * Using [`gulp-plumber`](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L110) to prevent stream from unpiping, adding [`.on('error', err => config.logger.error(err, dev))`](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/index.js#L141) to every step possibly throwing.
* Using [gulp 4](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/package.json#L14) (if using gulp). Probably not having an effect on "standard gulp tasks since they mostly use `gulp.src` and `gulp.dest` which [should not break anything for us](https://github.com/gulpjs/gulp/blob/4.0/CHANGELOG.md#400)
* Not using `gulp-util` which will be deprecated. Rather rely on the underlying modules (`plugin-error`, `fancy-log`, `chalk`, `minimist` etc.
* Documenting usage and options in [README.md](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/README.md)
* Adding [tests](https://github.com/unic/estatico-lerna/blob/master/packages/estatico-handlebars/test/index.js)

**Comment by drowka** [comment]
@backflip FYI I'll try to tackle CSS or SVG Sprite as I currently have some downtime. I'm not in the Unic group, but maybe an IT ticket can solve that :)

**Comment by Wymowny** [comment]
FYI; I'm in the middle of css:lint task

**Comment by backflip** [comment]
Thanks a bunch, @drowka and @Wymowny, I have added your packages to https://github.com/unic/estatico-lerna/tree/master/packages

**Comment by backflip** [comment]
Moved to https://github.com/unic/estatico-nou/issues/2
